services:
  backend:
    build:
      dockerfile: ./api/Dockefile
      context: ./
    env_file: ./api/.env
    networks: # isolate all networks so an attacker cannot escalate
      - db_link
      - s3_link
      - redis_link
    depends_on:
      - redis
      - postgresql
      - minio
  frontend:
    build:
      dockerfile: ./web/Dockefile
      context: ./
    env_file: ./web/.env
  redis:
    image: redis:latest
    env_file: ./.env.redis
    networks:
      - redis_link
  postgresql:
    image: postgres:latest
    restart: unless-stopped
    # set shared memory limit when using docker compose
    shm_size: 128mb
    env_file: ./.env.postgres
    networks:
      - db_link
  minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    env_file: ./.env.s3
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - s3_link

networks:
  default:
  db_link:
  s3_link:
  redis_link:

volumes:
  s3_storage:
  postgres_storage:
  redis_storage:
