secrets:
  api_env:
    file: devops/api/.env.production
  redis_env:
    file: .env.redis
  postgres_password:
    file: devops/postgres/.password
  postgres_user:
    file: devops/postgres/.user

services:
  api:
    build:
      dockerfile: Dockerfile
      context: api/
    secrets:
      - api_env
      - postgres_user
      - postgres_password
    environment:
      DJANGO_ENV_FILE: /run/secrets/api_env
      API_PORT: ${API_PORT:-7000}
      DBNAME: ${DBNAME:-etherbeing_db}
      DBHOST: postgres
      DBPORT: 5432
      DBUSER_FILE: /run/secrets/postgres_user
      DBPASS_FILE: /run/secrets/postgres_password
    volumes:
      - media_data:/app/src/etherbeing/media
    ports:
      - 127.0.0.1:${API_PORT:-7000}:${API_PORT:-7000}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  redis:
    # 6379
    image: redis:latest
    secrets:
      - redis_env
    volumes:
      - redis_data:/data
    restart: unless-stopped
  postgres:
    image: postgres:latest
    secrets:
      - postgres_user
      - postgres_password
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_DB=${DBNAME:-etherbeing_db}
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/
    restart: unless-stopped
volumes:
  postgres_data:
  media_data:
  redis_data:
