// This file is auto-generated by @hey-api/openapi-ts

export type AboutMe = {
    content: string;
    cv_file: string;
    name: string;
    photo: string;
    pitch: string;
    slogan: string;
};

export type ClientSerializer = {
    avatar?: string | null;
    id: number;
    logo: string;
    name: string;
    role?: string | null;
};

export type ContactPostSerializer = {
    email: string;
    message: string;
    name: string;
};

export type IndexResponse = {
    message: string;
};

export type LoginUser = {
    password: string;
    /**
     * can be also the email
     */
    username: string;
};

export type PortfolioItemSerializer = {
    client: ClientSerializer;
    description: string;
    image: string;
    portfolio_type: PortfolioType;
    project_date: number;
    public_url?: string | null;
    role: string;
    subtitle: string;
    title: string;
    youtube_url?: string | null;
};

export type PortfolioType = 'SimpleImage' | 'SimpleVideo' | 'Detailed';

export type RegisterUser = {
    country: number;
    email: string;
    google?: string | null;
    password: string;
    username: string;
};

export type CreatePortfolioItemData = {
    body: PortfolioItemSerializer;
    path?: never;
    query?: never;
    url: '/api/admin/portfolio/';
};

export type CreatePortfolioItemErrors = {
    /**
     * Credentials not valid for the current request
     */
    403: unknown;
};

export type CreatePortfolioItemResponses = {
    /**
     * Portfolio Item created successfully
     */
    201: unknown;
};

export type LoginData = {
    body: LoginUser;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Forbidden response
     */
    403: unknown;
};

export type LoginResponses = {
    /**
     * Authenticate the user
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Not authorized to perform this action
     */
    401: unknown;
};

export type LogoutResponses = {
    /**
     * Auth logout
     */
    200: unknown;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeResponses = {
    /**
     * Get the current user details
     */
    200: LoginUser;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Not authorized to perform this action
     */
    401: unknown;
};

export type RefreshResponses = {
    /**
     * Token refreshed
     */
    200: unknown;
};

export type RegisterData = {
    body: RegisterUser;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    /**
     * Get the current user details
     */
    200: unknown;
};

export type ContactData = {
    body: ContactPostSerializer;
    path?: never;
    query?: never;
    url: '/api/contact/';
};

export type ContactErrors = {
    /**
     * Forbidden response
     */
    403: unknown;
};

export type ContactResponses = {
    /**
     * Contact us
     */
    200: unknown;
};

export type GetInfoAboutMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/about/';
};

export type GetInfoAboutMeResponses = {
    /**
     * Obtain general values that describe the owner of the site and the site itself
     */
    200: unknown;
};

export type GetPortfolioData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/portfolio/';
};

export type GetPortfolioResponses = {
    200: Array<PortfolioItemSerializer>;
};

export type GetPortfolioResponse = GetPortfolioResponses[keyof GetPortfolioResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};