// This file is auto-generated by @hey-api/openapi-ts

export type ContactPostSerializer = {
    email: string;
    message: string;
    name: string;
};

export type IndexResponse = {
    message: string;
};

export type LoginUser = {
    password: string;
    /**
     * can be also the email
     */
    username: string;
};

export type RegisterUser = {
    country: number;
    email: string;
    google?: string | null;
    password: string;
    username: string;
};

export type LoginData = {
    body: LoginUser;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * Forbidden response
     */
    403: unknown;
};

export type LoginResponses = {
    /**
     * Authenticate the user
     */
    200: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * Not authorized to perform this action
     */
    401: unknown;
};

export type LogoutResponses = {
    /**
     * Auth logout
     */
    200: unknown;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeResponses = {
    /**
     * Get the current user details
     */
    200: LoginUser;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshErrors = {
    /**
     * Not authorized to perform this action
     */
    401: unknown;
};

export type RefreshResponses = {
    /**
     * Token refreshed
     */
    200: unknown;
};

export type RegisterData = {
    body: RegisterUser;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    /**
     * Get the current user details
     */
    200: unknown;
};

export type ContactData = {
    body: ContactPostSerializer;
    path?: never;
    query?: never;
    url: '/api/contact/';
};

export type ContactErrors = {
    /**
     * Forbidden response
     */
    403: unknown;
};

export type ContactResponses = {
    /**
     * Contact us
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};