// This file is auto-generated by @hey-api/openapi-ts

import { type Options, login, logout, me, refresh, register, contact } from '../sdk.gen';
import { type MutationOptions, type DefaultError, queryOptions } from '@tanstack/svelte-query';
import type { LoginData, LogoutData, MeData, RefreshData, RegisterData, ContactData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export const loginMutation = (options?: Partial<Options<LoginData>>): MutationOptions<unknown, DefaultError, Options<LoginData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>): MutationOptions<unknown, DefaultError, Options<LogoutData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const meQueryKey = (options?: Options<MeData>) => createQueryKey('me', options);

export const meOptions = (options?: Options<MeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await me({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: meQueryKey(options)
    });
};

export const refreshMutation = (options?: Partial<Options<RefreshData>>): MutationOptions<unknown, DefaultError, Options<RefreshData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerMutation = (options?: Partial<Options<RegisterData>>): MutationOptions<unknown, DefaultError, Options<RegisterData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await register({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const contactMutation = (options?: Partial<Options<ContactData>>): MutationOptions<unknown, DefaultError, Options<ContactData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<ContactData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await contact({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};