# Generated by Django 6.0 on 2025-12-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='title',
        ),
        migrations.AddField(
            model_name='blogentry',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
