# Generated by Django 6.0 on 2025-12-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_blogentry_author_remove_blogentry_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='github_id',
            field=models.CharField(default=None, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stargazers_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='watchers_count',
            field=models.IntegerField(default=None),
        ),
    ]
