# Generated by Django 6.0 on 2025-12-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_description_project_github_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
