# Generated by Django 6.0 on 2025-12-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_project_created_at_project_pushed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
