# Generated by Django 6.0 on 2025-12-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_blogentry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='html_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
