# Generated by Django 6.0 on 2025-12-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_project_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
