# Generated by Django 6.0 on 2025-12-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pushed_at',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
