# Generated by Django 6.0 on 2025-12-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_project_created_at_alter_project_pushed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
