# Generated by Django 6.0 on 2025-12-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_blogentry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='html_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
