# Generated by Django 6.0 on 2025-12-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_blogentry_html_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='blogentry',
            name='comments',
            field=models.ManyToManyField(null=True, to='base.blogentrycomment'),
        ),
    ]
