# Generated by Django 6.0 on 2025-12-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_blogentrycomment_blogentry_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='comments',
            field=models.ManyToManyField(to='base.blogentrycomment'),
        ),
    ]
