# Generated by Django 6.0 on 2025-12-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_blogentry_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentrycomment',
            name='content',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='blogentrycomment',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='blogentrycomment',
            name='username',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='blogentrycomment',
            name='github_id',
            field=models.CharField(default=None),
        ),
    ]
