# Generated by Codex on 2026-03-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_blogentrycomment_content_blogentrycomment_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(default="primary", unique=True)),
                ("site_title", models.CharField(max_length=255)),
                ("hero_titles", models.JSONField(blank=True, default=list)),
                ("hero_summary", models.TextField()),
                ("hero_cta_label", models.CharField(default="Download CV", max_length=255)),
                ("hero_cta_url", models.CharField(default="/cv.pdf", max_length=255)),
                ("about_short_bio", models.TextField()),
                ("buy_me_a_coffee_url", models.URLField(blank=True)),
                ("contact_intro", models.TextField()),
                ("footer_copy", models.CharField(max_length=255)),
                ("footer_tagline", models.CharField(max_length=255)),
                ("strategy_business_idea", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AboutHighlight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("column", models.CharField(choices=[("left", "Left"), ("right", "Right")], max_length=16)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("site_content", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="about_highlights", to="base.sitecontent")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("image_key", models.CharField(max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("site_content", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skills", to="base.sitecontent")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("starting_price", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("skills", models.JSONField(blank=True, default=list)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("site_content", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="services", to="base.sitecontent")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="ContactGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("site_content", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contact_groups", to="base.sitecontent")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="ContactLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=500)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links", to="base.contactgroup")),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
    ]
