# Generated by Django 4.2.28 on 2026-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_sitecontent_abouthighlight_contactgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='comments',
            field=models.ManyToManyField(blank=True, to='base.blogentrycomment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='stargazers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='watchers_count',
            field=models.IntegerField(default=0),
        ),
    ]
