# Generated by Codex on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_alter_project_description_alter_project_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
