# Generated by Codex on 2026-03-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_project_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentry",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
