# Generated by Django 4.2.28 on 2026-03-13 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def populate_service_slugs(apps, schema_editor):
    Service = apps.get_model("base", "Service")
    used_slugs = set()
    for service in Service.objects.all().order_by("id"):
        base_slug = slugify(service.title) or f"service-{service.pk}"
        slug = base_slug
        index = 2
        while slug in used_slugs:
            slug = f"{base_slug}-{index}"
            index += 1
        service.slug = slug
        service.save(update_fields=["slug"])
        used_slugs.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='deliverables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='engagement_cta',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.RunPython(populate_service_slugs, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS base_service_slug_e6de29de_like;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('contacted', 'Contacted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='base.service')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
