# Generated by Django 4.2.28 on 2026-03-13 15:43

from django.db import migrations, models

SKILL_DEFAULTS = {
    "Cybersecurity": {
        "image_url": "/skills/kali.png",
        "headline": "Offensive validation and defensive hardening",
        "description": "Practical security work spanning pentesting, audit, enumeration, and remediation support.",
    },
    "Rust": {
        "image_url": "/skills/rust.png",
        "headline": "Systems work with reliability in mind",
        "description": "High-confidence backend and systems development with an emphasis on correctness and performance.",
    },
    "Pentesting": {
        "image_url": "/skills/metasploit.png",
        "headline": "Exploit thinking for real-world release readiness",
        "description": "Attack-surface review and exploit-driven testing to expose meaningful security weaknesses before launch.",
    },
    "Biological Neural Nets": {
        "image_url": "/skills/tensorflow.png",
        "headline": "Research-oriented intelligence systems",
        "description": "Applied AI exploration informed by research, experimentation, and practical implementation constraints.",
    },
    "Python": {
        "image_url": "/skills/python.svg",
        "headline": "Fast iteration for APIs, tooling, and automation",
        "description": "Backend services, scripting, and automation pipelines that reduce friction and move quickly.",
    },
    "React TS": {
        "image_url": "/skills/react.svg",
        "headline": "Polished interactive product surfaces",
        "description": "Frontend systems with intentional UI structure, live data integration, and maintainable component design.",
    },
}


def populate_skill_card_fields(apps, schema_editor):
    Skill = apps.get_model("base", "Skill")
    for skill in Skill.objects.all():
        defaults = SKILL_DEFAULTS.get(skill.name)
        if not defaults:
            continue
        skill.image_url = defaults["image_url"]
        skill.headline = defaults["headline"]
        skill.description = defaults["description"]
        skill.save(update_fields=["image_url", "headline", "description"])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_service_deliverables_service_engagement_cta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='headline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.RunPython(populate_skill_card_fields, migrations.RunPython.noop),
    ]
