# .github/workflows/deploy.yml
name: Deploy Backend

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # Trigger on versioned releases like v1.0.0

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: actix-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Pull and restart container on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "Logging in to GHCR..."
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          echo "Stopping existing container..."
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

          echo "Pulling latest image..."
          docker pull $REGISTRY/${{ env.IMAGE_NAME }}:latest

          echo "Starting new container..."
          docker run -d \
            --restart always \
            --name $CONTAINER_NAME \
            -p 80:8080 \
            $REGISTRY/${{ env.IMAGE_NAME }}:latest
