# Please be aware that the frontend is not actually deployed we just the its deployability by integrating it in this pipeline
name: Deploy the full project

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: actix-backend

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Reveal secrets with git-secret
        run: |
          git secret reveal
      - name: Rebuild and update the image by using docker-compose
        run: docker compose up --build -d
  notify:
    uses: ./.github/workflows/ci_project.yml
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}