# Please be aware that the frontend is not actually deployed we just the its deployability by integrating it in this pipeline
name: Deploy the full project

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Reveal secrets with git-secret
        run: |
          git secret reveal
      - name: Remove container first FIXME use Swarm mode for a better upgrade experience
        run: docker compose down
      - name: Rebuild and update the image by using docker-compose
        run: docker compose up --build -d
  notify:
    needs: deploy
    if: always()
    uses: ./.github/workflows/ci_project.yml
    with:
      # Pass the final status of the job you want to report on
      status: ${{ needs.deploy.result }}
      # Pass required context for verbose messaging
      repo_name: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      commit_message: ${{ github.event.head_commit.message }}
      run_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
