#Integrate with social network to notify of changes and advance on the websites
name: Social networks notifications

on:
  workflow_call:
    secrets:
      DISCORD_WEBHOOK:
        required: true
      TELEGRAM_TOKEN:
        required: true
      TELEGRAM_TO:
        required: true

jobs:
  live_notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Success (Discord)
        if: success()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ✅ CI passed and Docker image pushed for ${{ github.repository }}!

      - name: Notify on Failure (Discord)
        if: failure()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ❌ CI failed for ${{ github.repository }}! Check logs.
      - name: Telegram notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Actix Web CI passed for ${{ github.repository }}!
